---
name: aggregate
version: 4
tags:
  - trade
namespace: CoreTx
description: Aggregate the info of each tx onto relevant states
type_urls:
  fg:t:aggregate: ForgeAbi.AggregateTx
proto: aggregate.proto
pipeline: protocol.yml
sources:
  - protocol.ex
